### ISSUE TITLE
Clicking on any Shoutcast or Icecast link does nothing

### ISSUE THREAD

**Issue by SanskritFritz** [tarmack/Pythagora#13]
~> pythagora

mpdunicode: Using python-mpd version 3.0 or later.
ERROR: Invalid browser function table. Some functionality may be restricted.
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
java version "1.6.0_24"
OpenJDK Runtime Environment (IcedTea6 1.11.1) (ArchLinux-6.b24_1.11.1-3-x86_64)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)
Traceback (most recent call last):
  File "/usr/share/Pythagora/plugins/IcecastForm.py", line 62, in _processLink
    self._playStation(urlString, urlMatch)
  File "/usr/share/Pythagora/plugins/IcecastForm.py", line 76, in _playStation
    adrlist = streamTools._parseM3U(data)
AttributeError: 'module' object has no attribute '_parseM3U'
Traceback (most recent call last):
  File "/usr/share/Pythagora/plugins/IcecastForm.py", line 62, in _processLink
    self._playStation(urlString, urlMatch)
  File "/usr/share/Pythagora/plugins/IcecastForm.py", line 74, in _playStation
    adrlist = streamTools._parseXSPF(data)
AttributeError: 'module' object has no attribute '_parseXSPF'
Traceback (most recent call last):
  File "/usr/share/Pythagora/plugins/ShoutcastForm.py", line 71, in _processLink
    self._playStation(url.toString())
  File "/usr/share/Pythagora/plugins/ShoutcastForm.py", line 80, in _playStation
    adrlist = streamTools._parsePLS(data)
AttributeError: 'module' object has no attribute '_parsePLS'
Traceback (most recent call last):
  File "/usr/share/Pythagora/plugins/ShoutcastForm.py", line 71, in _processLink
    self._playStation(url.toString())
  File "/usr/share/Pythagora/plugins/ShoutcastForm.py", line 80, in _playStation
    adrlist = streamTools._parsePLS(data)
AttributeError: 'module' object has no attribute '_parsePLS'

**Comment by tarmack** [comment]
Sorry I didn't come back to you earlier on this issue. I'm currently working 
on some big refactoring and this bug is solved when that comes to the master 
branch. If you don't mind waiting another week or so I prefer to hold this out 
till I can get the revised code in.

**Comment by SanskritFritz** [comment]
That is ok, just take your time, thanks for doing this anyway :)

**Comment by tarmack** [comment]
Finally had a chance to stabilise the changes I made along with some other improvements. The latest commit should fix a lot of small issues.

Thank you again for your feedback, it is always appreciated.

**Comment by SanskritFritz** [comment]
Nice work, thanks, radios work again beautifully.
