### ISSUE TITLE
Not connected to mpd

### ISSUE THREAD

**Issue by SanskritFritz** [tarmack/Pythagora#15]
pythagora does not connect to mpd, here is the output it writes to the terminal:

```
mpdunicode: Using python-mpd version 3.0 or later.
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
QSystemTrayIcon::setVisible: No Icon set
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
kbuildsycoca4 running...
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.58'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/Pythagora/mpdthreaded.py", line 285, in run
    func(*args)
  File "/usr/share/Pythagora/models/manager.py", line 62, in <lambda>
    lambda status, changes=changes: self._progressChanges(changes, status))
  File "/usr/share/Pythagora/models/manager.py", line 81, in _progressChanges
    self.playerState.update(status)
  File "/usr/share/Pythagora/models/state.py", line 102, in update
    self._setState('xFade', status['xfade'])
KeyError: 'xfade'


java version "1.7.0_45"
OpenJDK Runtime Environment (IcedTea 2.4.3) (ArchLinux build 7.u45_2.4.3-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.45-b08, mixed mode)
```

The program simply does nothing, no lists, no playlists, no directory listing whatsoever. The browser works.

**Comment by tarmack** [comment]
I moved to arch as well recently and noticed the issue, I made a quick fix. Now it is actually commited. :)

**Comment by SanskritFritz** [comment]
Welcome to Arch :)
Ok, now it's better, but the Library and Filesystem tabs are still empty.
I'm the maintainer of the pythagora-git package in the AUR, just tell me if you want to take it over.

**Comment by tarmack** [comment]
I'm not up for packaging for arch yet, maybe in the future.
You might want to remove the library cache from ~/.cache/pythagora. That should clear up the empty library if I'm not mistaken.
