### ISSUE TITLE
Latest python-mpd breaks Pythagora

### ISSUE THREAD

**Issue by mikeshutlar** [tarmack/Pythagora#4]
Using Arch Linux and python-mpd 0.3.0, Pythagora refuses to start with the following output:

```
Traceback (most recent call last):
  File "pythagora", line 379, in <module>
    main()
  File "pythagora", line 47, in main
    view = Manager(app)
  File "pythagora", line 62, in __init__
    self.mpdclient = mpd.MPDClient()
  File "/usr/share/Pythagora/mpdthreaded.py", line 49, in __init__
    self.connection = MPDThread(None, None, None, None)
  File "/usr/share/Pythagora/mpdthreaded.py", line 100, in __init__
    super(MPDThread, self).__init__()
  File "/usr/share/Pythagora/mpdunicode.py", line 41, in __init__
    self._commands.update({'rescan': self._getitem
  File "/usr/lib/python2.7/site-packages/mpd.py", line 166, in __getattr__
    (self.__class__.__name__, attr))
AttributeError: 'MPDThread' object has no attribute '_getitem'
```

Cheers :)

**Comment by tarmack** [comment]
The problem is: I subclassed the python-mpd module, but the new version has major changes. Thus breaking it. I'll have to look into a decent solution as for the comming time I think both versions should stay supported.

For now, you can work around the issue by placing the mpd.py file of the old version (0.2.1) in the root of Pythagora. I may just do that as an easy fix.

**Comment by tarmack** [comment]
Not the easy fix:). With some nice Python hackary I managed to get both versions working. It is now possible to use any version of the python-mpd library above 0.2.0.
